### PR TITLE
Fix issue 11 - Add wordlist validation + dedupe

### PR DESCRIPTION
**Pull request by jmiroosh**
Hi,
The tools is very good, thanks!

I was getting some strange errors with bad wordlist entries, so I have added whitelist validation, for issue #11

Also added a test in system.py, but unsure how to verify that it passes. (!!)

Thanks

### CODE REVIEW

**Comment by jamboro** [comment]
Actually, we could probably do with removing %/- and unicode chars from the wordlist too.

**Comment by nikitastupin** [comment]
Hey @jamboro (@jmiroosh)

Thank you for the pull request 😃 I have a few suggestions here

1. Let's move wordlist-related functions to a separate file (e.g. `clairvoyance/wordlist.py`). For example, create `clairvoyance/wordlist.py` with the following function and call the function in `__main__.py` to read the wordlist:

    ```
    $ cat clairvoyance/wordlist.py
    def read(filepath, validate):
        ...
    $ cat clairvoyance/__main__.py
    ...
    import wordlist
    ...
    w = wordlist.read(args.wordlist, args.validate)
    ...
    ```
    This will keep code cleaner which in turn would facilitate further contributions!
3. Instead of testing the feature at a system level (e.g. in `system.py`), let's do a test at the function level (e.g. create `wordlist_test.py` and test just the function).
4. The [`match`](https://docs.python.org/3/library/re.html#search-vs-match) would allow `ABC^` which isn't valid GraphQL name. I suggest use `re.search("^[_A-Za-z][_0-9A-Za-z]*$", w)` instead to fix this.

**Review by nikitastupin — CHANGES_REQUESTED** [review]
Hey @jamboro (@jmiroosh)

Thank you for the pull request 😃 I have a few suggestions here

1. Let's move wordlist-related functions to a separate file (e.g. `clairvoyance/wordlist.py`). For example, create `clairvoyance/wordlist.py` with the following function and call the function in `__main__.py` to read the wordlist:

    ```
    $ cat clairvoyance/wordlist.py
    def read(filepath, validate):
        ...
    $ cat clairvoyance/__main__.py
    ...
    import wordlist
    ...
    words = wordlist.read(args.wordlist, args.validate)
    ...
    ```
    This will keep code cleaner which in turn would facilitate further contributions!
3. Instead of testing the feature at a system level (e.g. in `system.py`), let's do a test at the function level (e.g. create `wordlist_test.py` and test just the function).
4. The [`match`](https://docs.python.org/3/library/re.html#search-vs-match) would allow `ABC^` which isn't valid GraphQL name. I suggest use `re.search("^[_A-Za-z][_0-9A-Za-z]*$", w)` instead to fix this.

**Comment by nikitastupin** [comment]
was refactored in #66 thanks for you contribution again!

**Pull request closed without merging**
